name: Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: install  # Ensures the install job runs before the test job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v4
        with:
          command: 'npx cypress run --component --headless'  # Specifies the Cypress command for component testing
