name: Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: |
          npx cypress install
          chmod +x ./node_modules/.bin/cypress  # Ensure Cypress binary is executable

      - name: Run Cypress Component Tests
        shell: bash
        run: |
          echo "Starting Cypress tests..."
          ./node_modules/.bin/cypress run --component --headless
