name: Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Explicitly using Node.js 20

      - name: Log Node.js Version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Check if Cypress test-component script exists
        run: |
          if ! npm run | grep -q 'test-component'; then
            echo "test-component script not found!" >&2
            exit 1
          fi

      - name: Run Cypress component tests
        run: npm run test-component
