name: Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress Installation
        run: npx cypress --version

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v4
        with:
          spec: 'cypress/component/**/*'   # Update to the actual path of your component tests
          browser: chrome
          working-directory: './'          # Ensure it runs in the correct directory
        env:
          CI: true                         # This ensures Cypress runs in CI mode
