name: Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Ensure this is the latest version
        with:
          node-version: '20'  # Use the latest stable version

      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is the latest version

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v5  # Ensure this is the latest version
        with:
          command: 'npx cypress run --component --headless'  # Use the command to run tests
