name: Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Log Node.js and Environment Details
        run: |
          node -v
          whoami
          pwd
          printenv | sort  # List environment variables for debugging
          ls -la  # List all files in root

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Verify Cypress Installation
        run: |
          ls -la ./node_modules/.bin/
          npx cypress --version

      - name: Run Cypress Component Tests
        run: |
          echo "Attempting to run Cypress tests..."
          chmod +x ./node_modules/.bin/cypress || true  # Ensure Cypress binary is executable
          npx cypress run --component
