name: Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ensure compatibility

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: |
          npm install cypress
          chmod +x ./node_modules/.bin/cypress  # Ensure Cypress binary is executable

      - name: Log Cypress Binary Location
        run: ls -la ./node_modules/.bin/  # Check if Cypress binary exists

      - name: Verify Cypress Installation
        run: npx cypress verify  # Verify installation

      - name: Run Cypress Component Tests
        run: npx cypress run --component --headless  # Run tests
