name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: '20'  # Standardize Node.js version to 20

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build  # Adjust if necessary

      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{}' ${{ secrets.RENDER_DEPLOY_HOOK }}
